export const FETCH_SONGS_REQUEST = "FETCH_SONGS_REQUEST";
export const FETCH_SONGS_FAILURE = "FETCH_SONGS_FAILURE";
export const FETCH_SONGS_SUCCESS = "FETCH_SONGS_SUCCESS";
export const RESET_SONGS = "RESET_SONGS";
